context:
  name: petsc4py
  version: "3.24.0a0"
  build: 0
  version_xy: ${{ (version | split('.'))[:2] | join('.') }}
  python_min: "3.10"

package:
  name: petsc4py
  version: ${{ version }}

source:
  # url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  url: https://gitlab.com/petsc/petsc/-/archive/b588a9366a03a8e02e0e9a612c549155ced7882d/petsc-main.tar.bz2
  sha256: 529d1cf1930ee421a70e86d09dac7ae001f8514b88f78caf326fab8f0ddb6eb6

build:
  number: ${{ build }}
  skip: win or (is_abi3 and not match(python, python_min + ".*"))
  python:
    version_independent: true
  script:
    content:
    - cd src/binding/petsc4py
    - ${{ PYTHON }} conf/cythonize.py
    - ${{ PYTHON }} -m pip -v install --no-deps .
    env:
      PETSC_DIR: "$PREFIX"
      PETSC4PY_BUILD_PYSABI: "1"

requirements:
  build:
    - ${{ compiler('fortran') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cython
        - cross-python_${{ target_platform }}
        - numpy
        - if: mpi == 'openmpi'
          then:
            - ${{ mpi }}
  host:
    - python
    - python-abi3
    - cython
    - pip
    - setuptools
    - numpy
    - ${{ mpi }}
    - if: device == 'host'
      then:
        - petsc ${{ version_xy }}.* ${{ scalar }}_*
      else:
        - petsc ${{ version_xy }}.* ${{ device }}_${{ scalar }}_*
  run:
    - python
  run_constraints:
    - mpi4py >=3.0.1

tests:
  - python:
      pip_check: true
      imports:
        - petsc4py
        - petsc4py.PETSc
      python_version:
        - ${{ python_min }}
        - "3.12"
        - "3.13"

  - script:
      - abi3audit $PREFIX/lib/python${{ python_min }}/site-packages/petsc4py/lib/*.so -s -v --assume-minimum-abi3 ${{ python_min }}
    requirements:
      run:
        - python ${{ python_min }}.*
        - abi3audit

about:
  summary: Python bindings for PETSc
  license: BSD-2-Clause
  license_file: LICENSE.rst
  homepage: https://petsc.org/release/petsc4py/

extra:
  recipe-maintainers:
    - dalcinl
    - minrk
    - davidbrochart
    - SylvainCorlay
    - stefanozampini
